Set up Project Skeleton
uclaacm/aws-lambda-node-js-template pull request #5
Opened 2022-12-31 22:02 UTC by JCamyre

2023-01-07 04:07 UTC, matthewcn56 requested changes
This is really great work, thanks for taking a stab at this Joseph! Looking at the github action logs and the AWS acct info this seems pretty solid, there's just some things I left for some more reliability, making it less error-prone, and changing the branches on which this runs under:
1 .We can set the name of the deployed function to be based off of the repo name within our org to ensure no name collisions based off of a package.json somehow.
2. Changing the workflows to only happen on pushes to MAIN, not any branch.

Later on, we should also change the name of this repo to be aws-lambda-node-js-template and we can make another repo called `aws-lambda-express-ts-template` to support express apps being deployed on lambda. We should also make these secrets org wide instead of repo wide so we can toggle on/off access to them from the admin perspective.

Overall, great work and I'm excited for us to use this soon!

2023-01-07 04:07 UTC, matthewcn56 commented on .github/workflows/claudia-update.yml
> +on: [push]
This currently has it so that whenever ANY branch pushes a commit, then we will update the deployment as well. However, I don't think that this is our intended behavior, and we want to make it so that only pushes to the MAIN branch will trigger deployments. An example of how to do this can be seen in the github action triggering workflows document under filters [here](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow)
<img width="796" alt="Screenshot 2023-01-06 at 7 34 15 PM" src="https://user-images.githubusercontent.com/65370631/211129479-fb93b21c-0265-42e2-a055-1551045406eb.png">

2023-01-07 04:07 UTC, matthewcn56 commented on app.ts
> +const express = require('express')
This current workflow is currently set-up to work with single lambda functions like within lambda.js, maybe we can set up a slightly different template repo to be used for Node.js express apps instead of singular functions? It's very similar and the documentation for how to do so with proxy wrappers can be seen [here](https://claudiajs.com/tutorials/serverless-express.html) inside a separate repo.

2023-01-07 04:07 UTC, matthewcn56 commented on .github/workflows/claudia-deploy.yml
> +        run: claudia create --region us-west-1 --handler lambda.handler --role ${{ secrets.CLAUDIA_IAM_ROLE }}
From the claudia docs, create by default uses the name inside the package.json. However, I think this can cause potential errors due to conflicts of having the same project name across projects within the package.json. I think the best way to do ensure that there aren't any conflicts is to use the repository name as there are guaranteed no conflicts within the uclaacm organization. A stack overflow post that goes over how to use that can be seen here: https://stackoverflow.com/questions/58467939/is-there-a-way-to-get-the-project-folder-name-only-on-a-github-action

2023-01-07 04:07 UTC, matthewcn56 commented on .github/workflows/claudia-update.yml
> +          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
Are these repository secrets or organization level secrets? Just curious as this can be a pretty nifty way for us to ensure that there's no malicious activity by manually toggling on secret access for a repository after we check to make sure that it's something safe, as seen [here](https://docs.github.com/en/actions/using-workflows/sharing-workflows-secrets-and-runners-with-your-organization)

2023-01-07 04:07 UTC, matthewcn56 commented on .github/workflows/claudia-update.yml
> +          if test -f "./claudia.json"; then
Another cool thing we can do is that we can ensure using the aws cli if the lambda function we want also exists if somehow a claudia.json is already made in the files but it might not've been deployed yet by us like documented [here](https://stackoverflow.com/questions/56532581/aws-cli-check-if-a-lambda-function-exists#:~:text=You%20can%20check%20the%20exit,function%2Dname%20my_lambda%20echo%20%24%3F).

This will be a separate issue though and we can try pushing this out first!

2023-01-07 04:07 UTC, matthewcn56 commented on .github/workflows/claudia-update.yml
> +            claudia test-lambda
This is good for debugging for now but when we push this out we probably should remove the test later since the execution of functions will differ from project to project.

2023-01-09 06:20 UTC, JCamyre commented on app.ts
> +const express = require('express')
Sounds good, will get on that soon.

2023-01-09 08:28 UTC, matthewcn56 requested changes
Haha I see from the commit history you've been doing a bunch of testing to see if the github actions work. I think that the changes are great, last thing we need to change is setting the **name** of the project in the `claudia-deploy` action to the name of the repository in the acm organization, however

2023-01-09 08:28 UTC, matthewcn56 commented on .github/workflows/claudia-deploy.yml
> +        run: claudia create --region us-west-1 --handler lambda.handler --role ${{ secrets.CLAUDIA_IAM_ROLE }}
I still think that we should use the `--name` option to set the name of the function we're deploying in the lambda console to be the name of the project as opposed to defaulting to the name inside the package.json

2023-01-09 08:28 UTC, matthewcn56 commented on package-lock.json
> +  "name": "claudia-test",
Small nit but instead of committing a package-lock.json, I think that we should use a yarn-lock by installing packages via yarn instead of npm to support our acm dev-team-wide shift from npm to yarn.

2023-01-13 06:35 UTC, matthewcn56 approved these changes
Great, thanks for separating everything, let's see if it works as a template 🤞

2023-01-13 06:35 UTC, matthewcn56 commented on .github/workflows/claudia-deploy.yml
> +on: [create]
Similarly to update, this should be just on the main branch as we don't want to run this function whenever **any** branch gets created.

2023-01-13 06:36 UTC, merged